package se.cambio.cds;
import se.cambio.cds.model.instance.ArchetypeReference;
import se.cambio.cds.model.instance.ElementInstance;
import se.cambio.cds.model.instance.ContainerInstance;
import se.cambio.cds.model.instance.FiredRuleReference;
import se.cambio.cds.util.DVUtil;
import org.openehr.rm.datatypes.quantity.DvOrdered;
import org.openehr.rm.datatypes.quantity.DvCount;
import org.openehr.rm.datatypes.quantity.DvOrdinal;
import org.openehr.rm.datatypes.quantity.DvQuantity;
import org.openehr.rm.datatypes.quantity.datetime.DvDate;
import org.openehr.rm.datatypes.quantity.datetime.DvDateTime;
import org.openehr.rm.datatypes.quantity.datetime.DvDuration;
import org.openehr.rm.datatypes.quantity.datetime.DvTime;
import org.openehr.rm.datatypes.quantity.DvProportion;
import org.openehr.rm.datatypes.quantity.ProportionKind;
import org.openehr.rm.datatypes.basic.DvBoolean;
import org.openehr.rm.datatypes.text.DvCodedText;
import org.openehr.rm.datatypes.text.DvText;
global se.cambio.cds.util.ExecutionLogger $executionLogger;
global org.openehr.rm.datatypes.basic.DataValue $auxDV;
global org.openehr.rm.datatypes.quantity.datetime.DvDateTime $currentDateTime;
global java.util.Map<se.cambio.cds.model.instance.ElementInstance, java.util.Map<String, Boolean>> $bindingMap;
global java.lang.Integer $CHA2DS2VAScdiagnosisreviewv1_salience;
global java.lang.Integer $StrokepreventioncompliancecheckinginAFv2_salience;

rule "CHA2DS2VASc_diagnosis_review.v1/gt0121"
salience $CHA2DS2VAScdiagnosisreviewv1_salience - 1
no-loop true
when
      $archetypeReference_gt0157:ArchetypeReference(idDomain=="EHR", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", archetypeReference==$archetypeReference_gt0157, predicate || dataValue instanceof Comparable, $predDV6:dataValue)
      not(      ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", DVUtil.areDomainsCompatible($archetypeReference_gt0157.getIdDomain(), archetypeReference.getIdDomain()),DVUtil.checkMaxMin($predDV6, dataValue, "max")))
      $gt0137:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0035]", archetypeReference==$archetypeReference_gt0157)
      $gt0138:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", archetypeReference==$archetypeReference_gt0157)
      $archetypeReference_gt0158:ArchetypeReference(idDomain=="CDS", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      $gt0114:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0035]", archetypeReference==$archetypeReference_gt0158)
      $archetypeReference_gt0159:ArchetypeReference(idDomain=="EHR", idArchetype=="openEHR-EHR-EVALUATION.problem-diagnosis.v1")
      $predicate7:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0002.1]", archetypeReference==$archetypeReference_gt0159)
      eval(DVUtil.isSubClassOf(true, $predicate7, $bindingMap, "CHA2DS2VASc_diagnosis_review.v1/gt0149", new DvCodedText[] {new DvCodedText("text","ICD10","I48")}))
      $gt0122:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0002.1]", archetypeReference==$archetypeReference_gt0159)
      $gt0125:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0003]", archetypeReference==$archetypeReference_gt0159)
      eval($gt0114.hasValue() && DVUtil.equalDV(false, $gt0114,new DvOrdinal(1,"Present","local","at0051"), true))
      eval($gt0122.hasValue())
      (eval($gt0137.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0137")) or eval($gt0125.hasValue() && $gt0138.hasValue() && DVUtil.compatibleComparison($gt0125.getDataValue(), $auxDV=$gt0138.getDataValue()) && DVUtil.compareDVs($gt0125.getDataValue(), $auxDV)>0))
then
      $gt0114.setDataValue(new DvOrdinal(1,"Present","local","at0051"));$gt0114.setNullFlavour(null);$executionLogger.addLog(drools, $gt0114);
      modify($gt0114){};
      insert(new FiredRuleReference("CHA2DS2VASc_diagnosis_review.v1", "gt0121"));
end

rule "CHA2DS2VASc_diagnosis_review.v1/gt0145"
salience $CHA2DS2VAScdiagnosisreviewv1_salience - 2
no-loop true
when
      $archetypeReference_gt0162:ArchetypeReference(idDomain=="EHR", idArchetype=="openEHR-EHR-EVALUATION.problem-diagnosis.v1")
      $predicate4:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0002.1]", archetypeReference==$archetypeReference_gt0162)
      eval(DVUtil.isSubClassOf(true, $predicate4, $bindingMap, "CHA2DS2VASc_diagnosis_review.v1/gt0100", new DvCodedText[] {new DvCodedText("text","ICD10","I50")}))
      $gt0110:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0002.1]", archetypeReference==$archetypeReference_gt0162)
      $gt0127:ElementInstance(id=="openEHR-EHR-EVALUATION.problem-diagnosis.v1/data[at0001]/items[at0003]", archetypeReference==$archetypeReference_gt0162)
      $archetypeReference_gt0157:ArchetypeReference(idDomain=="EHR", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", archetypeReference==$archetypeReference_gt0157, predicate || dataValue instanceof Comparable, $predDV6:dataValue)
      not(      ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", DVUtil.areDomainsCompatible($archetypeReference_gt0157.getIdDomain(), archetypeReference.getIdDomain()),DVUtil.checkMaxMin($predDV6, dataValue, "max")))
      $gt0140:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0038]", archetypeReference==$archetypeReference_gt0157)
      $gt0138:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", archetypeReference==$archetypeReference_gt0157)
      $archetypeReference_gt0158:ArchetypeReference(idDomain=="CDS", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      $gt0117:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0038]", archetypeReference==$archetypeReference_gt0158)
      eval($gt0117.hasValue() && DVUtil.equalDV(false, $gt0117,new DvOrdinal(1,"Present","local","at0051"), true))
      eval($gt0140.hasValue() && DVUtil.equalDV(false, $gt0140,new DvOrdinal(1,"Present","local","at0051"), false))
      (eval($gt0138.hasValue() && $gt0127.hasValue() && DVUtil.compatibleComparison($gt0138.getDataValue(), $auxDV=$gt0127.getDataValue()) && DVUtil.compareDVs($gt0138.getDataValue(), $auxDV)>0) or eval($gt0110.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0110")))
then
      $gt0117.setDataValue(new DvOrdinal(1,"Present","local","at0051"));$gt0117.setNullFlavour(null);$executionLogger.addLog(drools, $gt0117);
      modify($gt0117){};
      insert(new FiredRuleReference("CHA2DS2VASc_diagnosis_review.v1", "gt0145"));
end

rule "CHA2DS2VASc_diagnosis_review.v1/gt0027"
salience $CHA2DS2VAScdiagnosisreviewv1_salience - 0
no-loop true
when
      $archetypeReference_gt0158:ArchetypeReference(idDomain=="CDS", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      $gt0117:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0038]", archetypeReference==$archetypeReference_gt0158)
      $gt0118:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0039]", archetypeReference==$archetypeReference_gt0158)
      $gt0119:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0040]", archetypeReference==$archetypeReference_gt0158)
      $gt0124:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0041]", archetypeReference==$archetypeReference_gt0158)
      $gt0114:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0035]", archetypeReference==$archetypeReference_gt0158)
      $gt0115:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0036]", archetypeReference==$archetypeReference_gt0158)
      $gt0116:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0037]", archetypeReference==$archetypeReference_gt0158)
      eval($gt0124.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0124"))
      eval($gt0119.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0119"))
      eval($gt0118.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0118"))
      eval($gt0117.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0117"))
      eval($gt0116.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0116"))
      eval($gt0115.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0115"))
      eval($gt0114.hasNoValue("CHA2DS2VASc_diagnosis_review.v1/gt0114"))
then
      $gt0124.setDataValue(DVUtil.createDV($gt0124,"DV_DATE_TIME","value",$currentDateTime.getDateTime().getMillis()));$gt0124.setNullFlavour(null);$executionLogger.addLog(drools, $gt0124);
      $gt0119.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0119.setNullFlavour(null);$executionLogger.addLog(drools, $gt0119);
      $gt0118.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0118.setNullFlavour(null);$executionLogger.addLog(drools, $gt0118);
      $gt0117.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0117.setNullFlavour(null);$executionLogger.addLog(drools, $gt0117);
      $gt0116.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0116.setNullFlavour(null);$executionLogger.addLog(drools, $gt0116);
      $gt0115.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0115.setNullFlavour(null);$executionLogger.addLog(drools, $gt0115);
      $gt0114.setDataValue(new DvOrdinal(0,"Absent","local","at0050"));$gt0114.setNullFlavour(null);$executionLogger.addLog(drools, $gt0114);
      modify($gt0117){};
      modify($gt0118){};
      modify($gt0119){};
      modify($gt0124){};
      modify($gt0114){};
      modify($gt0115){};
      modify($gt0116){};
      insert(new FiredRuleReference("CHA2DS2VASc_diagnosis_review.v1", "gt0027"));
end

rule "Stroke_prevention_compliance_checking_in_AF.v2/gt0044"
salience $StrokepreventioncompliancecheckinginAFv2_salience - 0
no-loop true
when
      $archetypeReference_gt0046:ArchetypeReference(idDomain=="CDS", idArchetype=="openEHR-EHR-EVALUATION.cha2ds2vasc_compliance.v1")
      $gt0043:ElementInstance(id=="openEHR-EHR-EVALUATION.cha2ds2vasc_compliance.v1/data[at0001]/items[at0017]", archetypeReference==$archetypeReference_gt0046)
      $archetypeReference_gt0050:ArchetypeReference(idDomain=="CDS", idArchetype=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1")
      $gt0045:ElementInstance(id=="openEHR-EHR-EVALUATION.chadsvas_diagnosis_review.v1/data[at0001]/items[at0035]", archetypeReference==$archetypeReference_gt0050)
      $archetypeReference_gt0048:ArchetypeReference(idDomain=="EHR", idArchetype=="openEHR-EHR-INSTRUCTION.medication.v1")
      $predicate1:ElementInstance(id=="openEHR-EHR-INSTRUCTION.medication.v1/activities[at0001]/description[openEHR-EHR-ITEM_TREE.medication.v1]/items[at0012]", archetypeReference==$archetypeReference_gt0048)
      eval(DVUtil.isSubClassOf(true, $predicate1, $bindingMap, "Stroke_prevention_compliance_checking_in_AF.v2/gt0036", new DvCodedText[] {new DvCodedText("text","ATC","B01AA03"),new DvCodedText("text","ATC","B01AE07"),new DvCodedText("text","ATC","B01AF01"),new DvCodedText("text","ATC","B01AF02")}))
      $gt0026:ElementInstance(id=="openEHR-EHR-INSTRUCTION.medication.v1/activities[at0001]/description[openEHR-EHR-ITEM_TREE.medication.v1]/items[at0012]", archetypeReference==$archetypeReference_gt0048)
      eval($gt0045.hasValue() && DVUtil.equalDV(false, $gt0045,new DvOrdinal(1,"Present","local","at0051"), false))
      eval($gt0043.hasNoValue("Stroke_prevention_compliance_checking_in_AF.v2/gt0043"))
      eval($gt0026.hasNoValue("Stroke_prevention_compliance_checking_in_AF.v2/gt0026"))
then
      $gt0043.setDataValue(new DvCodedText("Absent","local","at0019"));$gt0043.setNullFlavour(null);$executionLogger.addLog(drools, $gt0043);
      modify($gt0043){};
      insert(new FiredRuleReference("Stroke_prevention_compliance_checking_in_AF.v2", "gt0044"));
end
