/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package se.cambio.cds.gdl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int SYM_MINUS = 7;
  /** RegularExpression Id. */
  int SYM_PLUS = 8;
  /** RegularExpression Id. */
  int SYM_STAR = 9;
  /** RegularExpression Id. */
  int SYM_SLASH = 10;
  /** RegularExpression Id. */
  int SYM_CARET = 11;
  /** RegularExpression Id. */
  int SYM_DOT = 12;
  /** RegularExpression Id. */
  int SYM_SEMICOLON = 13;
  /** RegularExpression Id. */
  int SYM_COMMA = 14;
  /** RegularExpression Id. */
  int SYM_TWO_COLONS = 15;
  /** RegularExpression Id. */
  int SYM_COLON = 16;
  /** RegularExpression Id. */
  int SYM_EXCLAMATION = 17;
  /** RegularExpression Id. */
  int SYM_L_PARENTHESIS = 18;
  /** RegularExpression Id. */
  int SYM_R_PARENTHESIS = 19;
  /** RegularExpression Id. */
  int SYM_DOLLAR = 20;
  /** RegularExpression Id. */
  int SYM_QUESTION = 21;
  /** RegularExpression Id. */
  int SYM_L_BRACKET = 22;
  /** RegularExpression Id. */
  int SYM_R_BRACKET = 23;
  /** RegularExpression Id. */
  int SYM_INTERVAL_DELIM = 24;
  /** RegularExpression Id. */
  int SYM_EQ = 25;
  /** RegularExpression Id. */
  int SYM_GE = 26;
  /** RegularExpression Id. */
  int SYM_LE = 27;
  /** RegularExpression Id. */
  int SYM_LT = 28;
  /** RegularExpression Id. */
  int SYM_GT = 29;
  /** RegularExpression Id. */
  int SYM_NE = 30;
  /** RegularExpression Id. */
  int SYM_NOT = 31;
  /** RegularExpression Id. */
  int SYM_AND = 32;
  /** RegularExpression Id. */
  int SYM_OR = 33;
  /** RegularExpression Id. */
  int SYM_FALSE = 34;
  /** RegularExpression Id. */
  int SYM_TRUE = 35;
  /** RegularExpression Id. */
  int SYM_NULL = 36;
  /** RegularExpression Id. */
  int SYM_IS_A = 37;
  /** RegularExpression Id. */
  int SYM_IS_NOT_A = 38;
  /** RegularExpression Id. */
  int SYM_FOR_ALL = 39;
  /** RegularExpression Id. */
  int SYM_CURRENT_DATETIME = 40;
  /** RegularExpression Id. */
  int SYM_ASSIGNMENT = 41;
  /** RegularExpression Id. */
  int SYM_MODULO = 42;
  /** RegularExpression Id. */
  int SYM_DIV = 43;
  /** RegularExpression Id. */
  int SYM_ELLIPSIS = 44;
  /** RegularExpression Id. */
  int SYM_LIST_CONTINUE = 45;
  /** RegularExpression Id. */
  int V_LOCAL_CODE_CORE = 46;
  /** RegularExpression Id. */
  int V_LOCAL_CODE = 47;
  /** RegularExpression Id. */
  int V_QUANTITY = 48;
  /** RegularExpression Id. */
  int V_PROPORTION = 49;
  /** RegularExpression Id. */
  int V_INTEGER = 50;
  /** RegularExpression Id. */
  int V_ISO8601_DURATION = 51;
  /** RegularExpression Id. */
  int V_ISO8601_DURATION_CONSTRAINT_PATTERN = 52;
  /** RegularExpression Id. */
  int V_DATE = 53;
  /** RegularExpression Id. */
  int V_HHMM_TIME = 54;
  /** RegularExpression Id. */
  int V_HHMMSS_TIME = 55;
  /** RegularExpression Id. */
  int V_HHMMSSss_TIME = 56;
  /** RegularExpression Id. */
  int V_HHMMSSZ_TIME = 57;
  /** RegularExpression Id. */
  int V_HHMMSSssZ_TIME = 58;
  /** RegularExpression Id. */
  int V_TIME = 59;
  /** RegularExpression Id. */
  int V_DATE_TIME_MS = 60;
  /** RegularExpression Id. */
  int V_DATE_TIME_Z = 61;
  /** RegularExpression Id. */
  int V_DATE_TIME = 62;
  /** RegularExpression Id. */
  int V_DATE_TIME_MSZ = 63;
  /** RegularExpression Id. */
  int DATE_TIME = 64;
  /** RegularExpression Id. */
  int TIME_ZONE = 65;
  /** RegularExpression Id. */
  int SECOND = 66;
  /** RegularExpression Id. */
  int MILLI_SECOND = 67;
  /** RegularExpression Id. */
  int HOUR_MINUTE = 68;
  /** RegularExpression Id. */
  int V_CODE_PHRASE = 69;
  /** RegularExpression Id. */
  int V_CODE_PHRASE_RAW = 70;
  /** RegularExpression Id. */
  int V_ORDINAL = 71;
  /** RegularExpression Id. */
  int V_ATTRIBUTE_IDENTIFIER = 72;
  /** RegularExpression Id. */
  int V_LABEL = 73;
  /** RegularExpression Id. */
  int V_REAL = 74;
  /** RegularExpression Id. */
  int V_STRING = 75;
  /** RegularExpression Id. */
  int DIG = 76;
  /** RegularExpression Id. */
  int LET_DIG = 77;
  /** RegularExpression Id. */
  int LET_DIG_DD = 78;
  /** RegularExpression Id. */
  int LET_DIG_U = 79;
  /** RegularExpression Id. */
  int LET_DIG_DU = 80;
  /** RegularExpression Id. */
  int LET_DIG_DUDS = 81;
  /** RegularExpression Id. */
  int LET_DIG_DUDSLR = 82;
  /** RegularExpression Id. */
  int V_LOCAL_TERM_CODE_REF = 83;
  /** RegularExpression Id. */
  int PATH_SEGMENT = 84;
  /** RegularExpression Id. */
  int V_ABSOLUTE_PATH = 85;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\".\"",
    "\";\"",
    "\",\"",
    "\"::\"",
    "\":\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"not\"",
    "<SYM_AND>",
    "<SYM_OR>",
    "\"false\"",
    "\"true\"",
    "\"null\"",
    "\"is_a\"",
    "\"!is_a\"",
    "\"for_all\"",
    "\"currentDateTime\"",
    "\"=\"",
    "\"\\\\\"",
    "\"//\"",
    "\"..\"",
    "\"...\"",
    "<V_LOCAL_CODE_CORE>",
    "<V_LOCAL_CODE>",
    "<V_QUANTITY>",
    "<V_PROPORTION>",
    "<V_INTEGER>",
    "<V_ISO8601_DURATION>",
    "<V_ISO8601_DURATION_CONSTRAINT_PATTERN>",
    "<V_DATE>",
    "<V_HHMM_TIME>",
    "<V_HHMMSS_TIME>",
    "<V_HHMMSSss_TIME>",
    "<V_HHMMSSZ_TIME>",
    "<V_HHMMSSssZ_TIME>",
    "<V_TIME>",
    "<V_DATE_TIME_MS>",
    "<V_DATE_TIME_Z>",
    "<V_DATE_TIME>",
    "<V_DATE_TIME_MSZ>",
    "<DATE_TIME>",
    "<TIME_ZONE>",
    "<SECOND>",
    "<MILLI_SECOND>",
    "<HOUR_MINUTE>",
    "<V_CODE_PHRASE>",
    "<V_CODE_PHRASE_RAW>",
    "<V_ORDINAL>",
    "<V_ATTRIBUTE_IDENTIFIER>",
    "<V_LABEL>",
    "<V_REAL>",
    "<V_STRING>",
    "<DIG>",
    "<LET_DIG>",
    "<LET_DIG_DD>",
    "<LET_DIG_U>",
    "<LET_DIG_DU>",
    "<LET_DIG_DUDS>",
    "<LET_DIG_DUDSLR>",
    "<V_LOCAL_TERM_CODE_REF>",
    "<PATH_SEGMENT>",
    "<V_ABSOLUTE_PATH>",
  };

}
